# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
run-name: "${{ github.event.inputs.run_id }}"

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Repository topic'
        required: true
      repo:
        description: 'Number of repositories to check'
        required: false
      run_id:
        description: 'Unique identifier for Workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch Go Program Repository
      run: git clone https://github.com/iamnihal/gh-archive.git gh-archive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build
      run: go build -v -o main .
      working-directory: ./gh-archive

    - name: Run
      run: ./gh-archive/main -t "${{ github.event.inputs.topic }}" -n "${{ github.event.inputs.repo }}" -o ./gh-archive/output.txt
      
    - name: Save Output
      uses: actions/upload-artifact@v2
      with:
        name: go-output
        path: ./gh-archive/output.txt

  access-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: go-output
        path: ./downloaded-artifact

    - name: Print Contents
      run: |
        cat ./downloaded-artifact/output.txt
